- action:
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_on
  alias: '1524201677'
  condition:
    condition: and
    conditions: []
  id: '1524201677'
  trigger:
  - at: '13:30'
    platform: time
- action:
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  alias: '1524201716'
  condition:
    condition: and
    conditions: []
  id: '1524201716'
  trigger:
  - entity_id: light.lnlight1a621
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  alias: '1524216535'
  id: '1524216535'
  trigger: 
  - platform: event
    event_type: event_sys_1_fire
