- action:
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  alias: '1521687250'
  condition:
    condition: and
    conditions: []
  id: '1521687250'
  trigger: []
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_off
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_off
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_off
  alias: '1521687327'
  condition:
    condition: and
    conditions: []
  id: '1521687327'
  trigger: []
